name: app
description: "Flutter riverpod clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.3+1
  auto_route: ^8.1.3
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.10+1
  local_auth: ^2.2.0
  local_auth_android: ^1.0.38
  local_auth_darwin: ^1.3.1
  hooks_riverpod: ^2.5.1  
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.0
  flutter_hooks: ^0.20.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/RedHatDisplay-blackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RedHatDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/RedHatDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplay-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/RedHatDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/RedHatDisplay-LightItalic.ttf
          weight: 300
          style: italic

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#5B06A1"
  image: assets/logo/launcher.png
  #branding: assets/logo/launcher.png
  android_12:
    image: assets/logo/launcher.png
    icon_background_color: "#5B06A1"
    #branding: assets/logo/launcher.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true


